### PR TITLE
Transfer chapter 3 (Identifying and defining)

### PR DESCRIPTION
**Pull request by zslade**
Addresses issue #9 

Chapter 3 (defining and identifying uncertainty) copied over and ready for review.

I think I've copied over everything correctly 🙏  and chosen sensible subtitles within sections but please check against the old version of the site as it's very possible I've missed something or make an error!

### CODE REVIEW

**Comment by ghpickering** [comment]
Started looking through this now

I think  _index.md needs to have weight = 2 added back in - otherwise the order of the chapters won't be correct in the sidebar as hugo defaults to ordering by most recent update when this is missing.

**Comment by zslade** [comment]
Thank you George! And good spot on all the accessibility bits.

Changes so far:
✅  weight=2 added back to the index page
✅ I've changed the bold text to <strong> tags for now. Since this is the only table, we could wait for the first accessibility audit and see what advice comes back and then update accordingly?
✅ Quasi section - I've removed the underlines. I was aiming for horizontal rules to break up the page but they weren't appearing in the browser. I think this is a problem with Hugo and the contrast of the horizontal rule it creates.

Will pick up the point about headings next 👍

**Comment by zslade** [comment]
I've updated headings from H3 to H2 in `Sources - assumptions.md` where a level was being skipped. I tried this in `Sources - data.md` too but I thought H2 headings looked a bit odd in places where there was a small amount of text so I have introduced a new H2 heading to keep everything else H3.

**Comment by ghpickering** [comment]
All looks good to me! - I noticed there was a missing link in `Defining uncertainty` so added this prior to merging.

**Pull request merged**
